management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          temperature: 0.9
      chat-review:
        options:
          temperature: 0.2
