name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/adam-466814/java-agent:latest .

    - name: Push Docker image
      run: docker push gcr.io/adam-466814/java-agent:latest

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials java-agent-cluster --zone us-central1 --project adam-466814
        sed -i "s|gcr.io/adam-466814/java-agent:latest|gcr.io/adam-466814/java-agent:$(git rev-parse --short HEAD)|" kubernetes/deployment.yaml
        kubectl apply -f kubernetes/deployment.yaml
